### ISSUE TITLE
Contact probability plot

### ISSUE THREAD

**Issue by jessakay** [mirnylab/cooltools#130]
Thank you for this great tool! I've been trying to generate figures similar to [1C](https://www.sciencedirect.com/science/article/pii/S0092867417311376#fig1) and [S1H](https://www.sciencedirect.com/science/article/pii/S0092867417311376#figs1) from the Bonev et al., 2017 paper.

It seemed to me that it should be very similar to the typical P(s) plot, and so I fiddled around with expected.compute_scaling per the [tutorial notebook](https://cooltools.readthedocs.io/en/latest/notebooks/01_scaling-curves.html), but in the end couldn't get it to work.

Are there any straightforward ways to tackle this with cooltools?

**Comment by mimakaev** [comment]
This is somewhat a nontrivial way to plot contact probability, without
dividing by bin size. Because bins are logarithmically spaced, the size of
the bin is proportional to s (genomic separation).  So mathematically their
method is equivalent to calculating an actual P(s) in any ordinary way, and
then multiplying it by s (the value on X axis) and not using logscale in Y.

I note that for calculating ordinary P(s) (with dividing by the bin size),
your result should not depend on the bins you use (are they logarithmic or
not, etc) - perhaps logarithmic bins would reduce noise, but they would not
affect the expected value. In their method, the result does depend on the
specific bins they use, and they specifically use logarithmically spaced
bins -  which mathematically multiplies P(s) by s. Which is why I don't
want to call it P(s), because mathematically it is P(s) * s.

In that notebook, you would just need to multiply scaling by dmeans, and
drop the Y axis logscale, you should get the correct plot.

That way of transforming P(s) does highlight the areas of genomic
separation from which most contacts are coming from, so it is useful in
that regard. One however can do the same analysis from looking at the
regular P(s) curve: most contacts are coming from the region where P(s) ~
s^-1 (when multiplied by s, those would be the "humps" on the curve). For
example, in mitotic chromosomes or prophase, P(s) changes from -0.5 at
s<10MB to -2 at s>10MB, and most contacts are coming from the transitional
area around s=10MB where the slope of P(s) is roughly -1.

**Comment by jessakay** [comment]
Oh now I get it! Thanks for the detailed explanation and helpful suggestions :)
