### ISSUE TITLE
Origin of 'weight1' and 'weight2' columns in cooler.annotate() output dataframe?

### ISSUE THREAD

**Issue by bperl1** [mirnylab/cooltools#181]
I am trying to normalize the data in my .cool files using an expected distance decay model. In some of the tutorial/example programs on cooltools.readthedocs.io, I noticed that the transformation `'balanced': lambda p: p['count'] * p['weight1'] * p['weight2']` is applied to the annotated bin/pixel matrix (through _diagsum_symm() in the .diagsum() function) to create expected contact frequencies using what I'm assuming is a distance decay model. Could you please explain what types of balancing the 'weight1' and 'weight2' columns in the annotated bin/pixel matrix reflect, and how p['weight1'] * p['weight2'] creates a weight that can be used for distance decay normalization?

**Comment by sergpolly** [comment]
@bperl1 it all comes down to the way cooler stores data about pairwise genomic interactions:  a [table](https://cooler.readthedocs.io/en/latest/datamodel.html#pixels) of non-zero pixels is stored instead of storing all interactions in a matrix format. Each pixels represents an interaction between a pair of genomic bins -> `bin1_id, bin2_id, count`, where `count` is total number of raw interactions in the pixel. When you annotate a table of pixels, cooler is grabbing information about each bin from [`clr.bins()`-table](https://cooler.readthedocs.io/en/latest/datamodel.html#bins) and appends it to pixel table. Because each pixel is formed by a pair of bins, annotation appends info about each of them and adds a suffix `1` , for `bin1_id` and `2` for `bin2_id` -> that's where `weight1` and `weight2` pop up .

`weight` by itself is a multiplicative normalization factor, thus `p['count'] * p['weight1'] * p['weight2']` - is simply giving you balanced (nromalized)  genomic interactions (frequency of interactions) on the fly - read https://www.nature.com/articles/nmeth.2148 to get more info on balancing. So point is cooler does not store balanced data, and instead applies balancing when needed.

"distance decay expected" is an average of interactions at a given "distance" between a pair of loci, which is typically calculated on balanced data (most of the analyses are done on balanced data), hence you supply this data transformation: `'balanced': lambda p: p['count'] * p['weight1'] * p['weight2']` and the `balanced` column is what going to be averaged for every genomic distance (diag, genomic separation etc).

**Comment by bperl1** [comment]
Oh that makes sense. Thanks so much for the help!
