### ISSUE TITLE
compute saddle plot

### ISSUE THREAD

**Issue by LeilyR** [mirnylab/cooltools#30]
Hi, Do you have any test data that I could see how a track-path and expected-path file actually look like? I have already had an exp/obs matrix and would like to generate a saddle plot using your tool.

**Comment by nvictus** [comment]
Take a look at these notebooks:

https://github.com/hms-dbmi/hic-data-analysis-bootcamp/tree/master/notebooks

There are links to raw data in the repo README and instructions to reproduce the analysis.

**Comment by LeilyR** [comment]
Thanks a million. May I ask how do the exp and eig files in computing saddle plot look. I mean their format and what they have in each column and each row i couldn't find them under hic-data-analysis-bootcamp/notebooks/data/ . I would like to input files which were already generated by another tools it will be very helpful since I could convert them to a format that is accepted by cootools.

**Comment by nvictus** [comment]
Sure! The two files are TSVs with a header line. Note that these conventions are in flux as we experiment with more flexible representations and interfaces, and better defaults.

The exp file depends on whether you are making saddle plots from _cis_ or _trans_ data. To see an example, they can be generated by the `compute_expected` tool.

For cis data, the exp file should have columns: 
1. `chrom`
2. `diag`: diagonal index, starting from 0
3. `n_valid`: the number of valid elements on a given diagonal (total number of elements minus pixels corresponding to "bad bins" filtered out during normalization).
4. a value column that can be specified by name using the syntax `<file_path>::<column_name>` if not the 4th column. Right now, the default is assumed to be called `balanced.avg`, i.e. the sum of balanced values on the diagonal divided by n_valid.

For trans data, the exp file should have columns:
1. `chrom1`
2. `chrom2`
3. `n_valid`: number of valid elements in an interchromosomal block (total number of elements minus bad pixels)
4. a value column, default being `balanced.avg`, as above.

The eig file is more straightforward. It is assumed to be a generalized [bedGraph](https://genome.ucsc.edu/goldenpath/help/bedgraph.html) file: `chrom`, `start`, `end`, `value`; however, it accepts the syntax `<file_path>::<column_name>` to specify a value column, e.g. if there are several extra columns in the file. The default value column is assumed to be named `E1`, as that is the output from the eigendecomposition tool.

You can see the steps of saddleplot creation broken down in [this notebook](https://github.com/hms-dbmi/hic-data-analysis-bootcamp/blob/master/notebooks/04_analysis_cooltools-eigenvector-saddle.ipynb), where you'll have more flexibility than with the CLI. I would also recommend that if you use quantile binning of the signal track (which I also recommend), then you can plot median signal values on the margins of the saddle plot, rather than signal histograms which are flat by definition. This was changed on the `develop` branch.

**Comment by LeilyR** [comment]
Thank you so much! It was really helpful. There is one technical thing which I try to get my head around it. It would be so kind as if you could tell me how the rows and column in the __accumulate function in saddle.py are chosen to be masked and why.  Also setting diagonal values to {2, 0,-2 , 1 , -1} results in divide by 0 in the next step when sum /count.

**Comment by nvictus** [comment]
Sure. So the steps to making a saddle plot are

1. We assign discrete ranks to (i.e. we "quantize" or "digitize") each of the scores of a signal track `s`, such as an eigenvector, according to some partition of the score value range (e.g. by partitioning into quantile intervals). Each digit assignment (0, 1, 2, ...) then corresponds to a subset of genomic bins `i`, where each `s[i]` falls in the corresponding quantile interval (e.g. [-1, -0.75)).

2. Generate a saddle map (in this case, we accumulate the sums `S` and counts `C` separately) from the desired contact matrix `M` (in this case, an observed/expected submatrix). The saddle pixel `S[a, b]` corresponds to the sum of all matrix elements `M[i, j]` such that `s[i]` is assigned the digit `a` and `s[j]` is assigned the digit `b`. 

I'm pasting the function below with comments and modified variable names to hopefully make it clearer. For each pair of digit assignments `i` and `j`, we obtain a boolean mask of all genomic bins assigned those digits, and use those masks to select the pixels from `M` that satisfy (2) above. 

```python
def _accumulate(S, C, getmatrix, digitized, chrom1, chrom2, verbose):
    n_digits = S.shape[0]

    # get the submatrix of observed/expected
    matrix = getmatrix(chrom1, chrom2)

    # mask out first two diagonals (where Hi-C artifacts live)
    if chrom1 == chrom2:
        for d in [-2, -1, 0, 1, 2]:
            numutils.set_diag(matrix, np.nan, d)

    if verbose:
        print('chromosomes {} vs {}'.format(chrom1, chrom2))
        
    for a in range(n_digits):
        row_mask = (digitized[chrom1] == a)
        for b in range(n_digits):
            col_mask = (digitized[chrom2] == b)
            # select all pixels whose row index has digit assignment a 
            # and whose column index has digit assignment b
            data = matrix[row_mask, :][:, col_mask]
            data = data[np.isfinite(data)]  # drop NaNs
            S[i, j] += np.sum(data)
            C[i, j] += float(len(data))
```

If it's still too abstract, let me know. Maybe I can make a small toy example.

**Comment by LeilyR** [comment]
Thank you so much! It was a great explanation and made things much clearer in my mind. However if you don't mind, I would like to ask you about the criteria which has been applied to choose the number of partitions.  Like 'histbins = 30' that has been chosen for the example in the python notebook, since at the end this number basically defines the shape of the saddle data, if i am not wrong.

**Comment by nvictus** [comment]
That's right. 30 partitions is just a reasonable size from experience: gives good contrast but is reasonably fast to compute. But it depends on data resolution: for very sparse data like single-cell Hi-C, you typically have to bin very coarsely (e.g. 5x5) to get a good looking saddle plot. 

In the case of quantile binning, at the limit of # partitions -> size of the contact matrix, you would end up with a simple permutation of the rows and columns of the original contact matrix, in the order of ascending eigenvector score.

**Comment by LeilyR** [comment]
Thanks a million!
